### ISSUE TITLE
String crafting crash

### ISSUE THREAD

**Issue by benjiben55** [ValhelsiaTeam/Valhelsia#105]
Hello, when i start the game and put a string into the crafting folder the game crasg with null point error.
At the screen is a warning with a recipe conflict see log below.

Btw. thanks for the cool modpack

sincerely benjiben

---- Minecraft Crash Report ----
// You're mean.

Time: 6/24/20 5:55 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: null
	at it.unimi.dsi.fastutil.ints.IntArrays.forceCapacity(IntArrays.java:122) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.ints.IntArrayList.grow(IntArrayList.java:244) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.ints.IntArrayList.add(IntArrayList.java:259) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at net.minecraft.item.crafting.Ingredient.func_194139_b(Ingredient.java:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at shadows.placebo.recipe.FastShapelessRecipe.func_77569_a(FastShapelessRecipe.java:40) ~[?:3.0.2] {re:classloading}
	at shadows.placebo.recipe.FastShapelessRecipe.func_77569_a(FastShapelessRecipe.java:15) ~[?:3.0.2] {re:classloading}
	at net.minecraft.item.crafting.IRecipeType.func_222148_a(SourceFile:29) ~[?:?] {re:classloading}
	at net.minecraft.item.crafting.RecipeManager.lambda$getRecipes$3(RecipeManager.java:87) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraft.item.crafting.RecipeManager.func_215370_b(RecipeManager.java:90) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at top.theillusivec4.polymorph.client.RecipeConflictManager.fetchRecipes(RecipeConflictManager.java:185) ~[?:FORGE-1.15.2-0.2] {re:classloading}
	at top.theillusivec4.polymorph.client.RecipeConflictManager.lambda$null$2(RecipeConflictManager.java:150) ~[?:FORGE-1.15.2-0.2] {re:classloading}
	at java.util.Optional.orElseGet(Unknown Source) ~[?:1.8.0_251] {}
	at top.theillusivec4.polymorph.client.RecipeConflictManager.lambda$tick$4(RecipeConflictManager.java:150) ~[?:FORGE-1.15.2-0.2] {re:classloading}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_251] {}
	at top.theillusivec4.polymorph.client.RecipeConflictManager.tick(RecipeConflictManager.java:144) ~[?:FORGE-1.15.2-0.2] {re:classloading}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_251] {}
	at top.theillusivec4.polymorph.client.ClientEventHandler.tick(ClientEventHandler.java:49) ~[?:FORGE-1.15.2-0.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1380_ClientEventHandler_tick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:109) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1449) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:904) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.21.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at it.unimi.dsi.fastutil.ints.IntArrays.forceCapacity(IntArrays.java:122)
	at it.unimi.dsi.fastutil.ints.IntArrayList.grow(IntArrayList.java:244)
	at it.unimi.dsi.fastutil.ints.IntArrayList.add(IntArrayList.java:259)
	at net.minecraft.item.crafting.Ingredient.func_194139_b(Ingredient.java:94)
	at shadows.placebo.recipe.FastShapelessRecipe.func_77569_a(FastShapelessRecipe.java:40)
	at shadows.placebo.recipe.FastShapelessRecipe.func_77569_a(FastShapelessRecipe.java:15)
	at net.minecraft.item.crafting.IRecipeType.func_222148_a(SourceFile:29)
	at net.minecraft.item.crafting.RecipeManager.lambda$getRecipes$3(RecipeManager.java:87)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at net.minecraft.item.crafting.RecipeManager.func_215370_b(RecipeManager.java:90)
	at top.theillusivec4.polymorph.client.RecipeConflictManager.fetchRecipes(RecipeConflictManager.java:185)
	at top.theillusivec4.polymorph.client.RecipeConflictManager.lambda$null$2(RecipeConflictManager.java:150)
	at java.util.Optional.orElseGet(Unknown Source)
	at top.theillusivec4.polymorph.client.RecipeConflictManager.lambda$tick$4(RecipeConflictManager.java:150)
	at java.util.Optional.ifPresent(Unknown Source)
	at top.theillusivec4.polymorph.client.RecipeConflictManager.tick(RecipeConflictManager.java:144)
	at java.util.Optional.ifPresent(Unknown Source)
	at top.theillusivec4.polymorph.client.ClientEventHandler.tick(ClientEventHandler.java:49)
	at net.minecraftforge.eventbus.ASMEventHandler_1380_ClientEventHandler_tick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:109)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Benjibentown'/85, l='MpServer', x=6728.99, y=64.00, z=-5496.93]]
	Chunk stats: Client Chunk Cache: 625, 361
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -6762365088210691588
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (96,63,-107), Chunk: (at 0,3,5 in 6,-7; contains blocks 96,0,-112 to 111,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 3096900 game time, 4200950 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:572)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 975405160 bytes (930 MB) / 4754501632 bytes (4534 MB) up to 8254586880 bytes (7872 MB)
	CPUs: 4
	JVM Flags: 18 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8073m -Xms256m -XX:PermSize=256m -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -XX:+DisableExplicitGC
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.21.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.21.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.21.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.21.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre30.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.21.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.21
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		aiotbotania-1.15.2-1.2.2.jar AIOT Botania {aiotbotania@1.2.2 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		mcw-windows-1.0.1-mc1.15.2_1.15.1.jar Macaw's Windows {mcwwindows@1.0.1 DONE}
		SilentMechanisms-1.15.2-0.7.2+52.jar Silent's Mechanisms {silents_mechanisms@0.7.2+52 DONE}
		Neat 1.6-22.jar Neat {neat@1.6-22 DONE}
		essentials-1.15.2-2.7.2.jar Essentials {essentials@1.15.2-2.7.2 DONE}
		TerraForged-1.15.2-0.0.14.jar TerraForged {terraforged@0.0.14 DONE}
		BetterTitleScreen-1.15.2-1.9.jar Better Title Screen {bettertitlescreen@1.15.2-1.9 DONE}
		XaerosWorldMap_1.6.4_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.6.4 DONE}
		CookingForBlockheads_1.15.2-8.0.2.jar Cooking for Blockheads {cookingforblockheads@8.0.2 DONE}
		Controlling-6.1.4.jar Controlling {controlling@6.1.4 DONE}
		ReAuth-1.14-1.15-3.8.1.jar ReAuth {reauth@3.8.1 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		globaldatapack-1.15.2-1.3.jar Dark Roleplay - Global Datapacks {globaldatapack@1.15.2-0.1.0 DONE}
		Powah-1.15.2-1.1.14.jar Powah {powah@1.1.14 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		u_team_core-1.15.2-2.12.1.158.jar U Team Core {uteamcore@2.12.1.158 DONE}
		randompatches-1.15.2-1.21.1.2.jar RandomPatches {randompatches@1.15.2-1.21.1.2 DONE}
		DarkUtilities-1.15.2-3.0.6.jar Dark Utilities {darkutils@3.0.6 DONE}
		Apotheosis-1.15.2-3.1.2.jar Apotheosis {apotheosis@3.1.2 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		mcw-doors-1.0.0-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		MekanismGenerators-1.15.2-9.10.8.421.jar Mekanism: Generators {mekanismgenerators@9.10.8 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 DONE}
		absentbydesign-1.15.2-1.0.7.jar Absent By Design Mod {absentbydesign@1.15.2-1.0.7 DONE}
		refinedstorage-1.8.5.jar Refined Storage {refinedstorage@1.8.5 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		lightestlamp-3.4.2.jar Lightest Lamps {lightestlamp@3.4.2 DONE}
		industrial-foregoing-1.15.2-2.3.3-e356e61.jar Industrial Foregoing {industrialforegoing@2.3.3 DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		embellishcraft-1.15.2-2.2.0.0.jar EmbellishCraft {embellishcraft@1.15.2-2.2.0.0 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		BiomesOPlenty-1.15.2-10.0.0.365-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.365 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		MekanismAdditions-1.15.2-9.10.8.421.jar Mekanism: Additions {mekanismadditions@9.10.8 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		Lollipop-1.15.2-1.0.15.jar Lollipop {lollipop@1.0.15 DONE}
		SilentGear-1.15.2-1.7.5+106.jar Silent Gear {silentgear@1.7.5+106 DONE}
		simplefarming-1.15.2-1.2.9.jar Simple Farming {simplefarming@1.15.2-1.2.9 DONE}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Botania-r1.15-386.jar Botania {botania@r1.15-386 DONE}
		Patchouli-1.15.2-1.2-34.jar Patchouli {patchouli@1.15.2-1.2-34 DONE}
		extlights-2.0.jar Extended Lights {extlights@2.0 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		MekanismTools-1.15.2-9.10.8.421.jar Mekanism: Tools {mekanismtools@9.10.8 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		cc-tweaked-1.15.2-1.89.0.jar CC: Tweaked {computercraft@1.89.0 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		cherishedworlds-FORGE-1.15.2-3.0.jar Cherished Worlds {cherishedworlds@FORGE-1.15.2-3.0 DONE}
		bwncr-1.15.1-3.6.13.jar Bad Wither No Cookie Reloaded {bwncr@1.15.1-3.6.13 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		CodeChickenLib-1.15.2-3.3.0.373-universal.jar CodeChicken Lib {codechickenlib@3.3.0.373 DONE}
		leavesdecayonotherleaves-1.1.jar Leaves Decay on other Leaves {leavesdecayonotherleaves@1.1 DONE}
		CraftPresence-1.15.2-1.6.5.jar CraftPresence {craftpresence@1.6.5 DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		torchslabmod-1.15.2_v1.6.15.jar Torch Slab Mod {torchslabmod@1.6.15 DONE}
		EquipmentTooltips-1.15.2-1.4.3+14.jar Equipment Tooltips {equipmenttooltips@1.4.3+14 DONE}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		PersistentBits-1.15.2-2.0.2.jar Persistent Bits {persistentbits@2.0.1 DONE}
		jei-1.15.2-6.0.1.5.jar Just Enough Items {jei@6.0.1.5 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Buzzier-Bees-1.15.2-1.5.1.jar Buzzier Bees {buzzierbees@1.5.1 DONE}
		Mekanism-1.15.2-9.10.8.421.jar Mekanism {mekanism@9.10.8 DONE}
		caelus-FORGE-1.15.2-2.0-beta3.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta3 DONE}
		Upgrade-Aquatic-1.15.2-v1.6.1.jar Upgrade Aquatic {upgrade_aquatic@1.6.1 DONE}
		reap-1.12.5.jar Reap Mod {reap@1.12.5 DONE}
		WAWLA-1.15.2-3.0.2.jar WAWLA {wawla@3.0.2 DONE}
		create-mc1.15.2_v0.2.4d.jar Create {create@mc1.15.2_v0.2.4d DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		LightOverlay-4.6.1.jar Light Overlay Forge {lightoverlay-forge@4.6.1 DONE}
		comforts-FORGE-1.15.2-2.0.0.3.jar Comforts {comforts@FORGE-1.15.2-2.0.0.3 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		FruitTrees-1.15.2-1.4.1.jar Fruit Trees {fruittrees@1.4.1 DONE}
		Kiwi-1.15.2-2.7.1.jar Kiwi {kiwi@2.7.1 DONE}
		SimpleStorageNetwork-1.15.2-0.3.2.jar Simple Storage Network {storagenetwork@1.15.2-0.3.2 DONE}
		SereneSeasons-1.15.2-3.0.0.72-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.72 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		BotanyPots-1.15.2-2.0.17.jar BotanyPots {botanypots@2.0.17 DONE}
		curioofundying-FORGE-1.15.2-3.0.jar Curio of Undying {curioofundying@FORGE-1.15.2-3.0 DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.1.jar The Endergetic Expansion {endergetic@1.3.1 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		mcjtylib-1.15-4.1.1-beta.jar McJtyLib {mcjtylib@1.15-4.1.1-beta DONE}
		rftoolsbase-1.15-1.1.1-beta.jar RFToolsBase {rftoolsbase@1.15-1.1.1-beta DONE}
		xnet-1.15-2.1.5-beta.jar XNet {xnet@1.15-2.1.5-beta DONE}
		rftoolsstorage-1.15-1.1.4-beta.jar RFToolsStorage {rftoolsstorage@1.15-1.1.4-beta DONE}
		rftoolscontrol-1.15-3.0.2-beta.jar RFToolsControl {rftoolscontrol@1.15-3.0.2-beta DONE}
		mapperbase-1.15.2-1.1.0.0.jar Mapper Base {mapperbase@1.15.2-1.1.0.0 DONE}
		trash-1.15.2-0.1.4.jar Trash {trash@1.15.2-0.1.4 DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		mininggadgets-1.3.5.jar Mining Gadgets {mininggadgets@1.3.5 DONE}
		EnderStorage-1.15.2-2.5.0.143-universal.jar EnderStorage {enderstorage@2.5.0.143 DONE}
		rftoolspower-1.15-2.1.1-beta.jar RFToolsPower {rftoolspower@1.15-2.1.1-beta DONE}
		extradisks-1.15.2-1.2.2.jar Extra Disks {extradisks@1.15.2-1.2.2 DONE}
		Swamp-Expansion-1.15.2-v1.7.1.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.2.21-universal.jar Forge {forge@31.2.21 DONE}
		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 DONE}
		WailaHarvestability-mc1.15.2-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 DONE}
		forge-1.15.2-31.2.21-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.4.0b.jar CoFH Core {cofh_core@0.4.0b DONE}
		ensorcellation-1.15.2-0.4.1b.jar Ensorcellation {ensorcellation@0.4.1b DONE}
		rftoolsutility-1.15-2.1.3-beta.jar RFToolsUtility {rftoolsutility@1.15-2.1.3-beta DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.15.2-1.14.1.jar Tool Belt {toolbelt@1.14.1 DONE}
		titanium-1.15.2-2.4.2.jar Titanium {titanium@2.4.2 DONE}
		Psi r1.2-82.jar Psi {psi@r1.2-80 DONE}
		ImmersiveEngineering-0.15-103.jar Immersive Engineering {immersiveengineering@0.15-101 DONE}
		SilentLib-1.15.2-4.6.3+55.jar Silent Lib {silentlib@4.6.3+55 DONE}
		forbidden_arcanus-1.15.2-1.4-beta-2.jar Forbidden & Arcanus {forbidden_arcanus@1.15.2-1.4-beta-2 DONE}
		archers_paradox-1.15.2-0.4.0b.jar Archer's Paradox {archers_paradox@0.4.0b DONE}
		Atmospheric-1.15.2-1.4.0.jar Atmospheric {atmospheric@1.4.0 DONE}
		rftoolsbuilder-1.15-2.1.3-beta.jar RFToolsBuilder {rftoolsbuilder@1.15-2.1.3-beta DONE}
		MiscAdditions-1.2.3.jar Misc Additions {miscadditions@1.2.3 DONE}
		jeiintegration_1.15.2-3.1.0.1.jar JEI Integration {jeiintegration@3.1.0.1 DONE}
		Xaeros_Minimap_20.14.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.14.0 DONE}
		JAOPCA-1.15.2-3.2.0.11.jar JAOPCA {jaopca@3.2.0.11 DONE}
		ftb-backups-2.1.0.1.jar FTB Utilities: Backups {ftbbackups@2.1.0.1 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		autumnity-1.3.2-1.15.2.jar Autumnity {autumnity@1.3.2 DONE}
		polymorph-FORGE-1.15.2-0.2.jar Polymorph {polymorph@FORGE-1.15.2-0.2 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		FluxNetworks-1.15.2-5.0.1-2.jar Flux Networks {fluxnetworks@1.15.2-5.0.1-2 DONE}
		DoubleSlabs-1.15-2.6.1.jar Double Slabs {doubleslabs@2.6.1 DONE}
		themidnight-0.5.9.jar The Midnight {midnight@0.5.9 DONE}
		structurize-0.10.324-ALPHA.jar Structurize {structurize@0.10.324-ALPHA DONE}
		fancymenu_1.3_MC_1.15-1.15.2.jar §dFancy§5Menu {fancymenu@1.3 DONE}
		minecolonies-1.15.2-0.11.960-universal.jar Minecolonies {minecolonies@1.15.2-0.11.960 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		Aquaculture-1.15.2-2.0.14.jar Aquaculture 2 {aquaculture@1.15.2-2.0.14 DONE}
		refinedstorageaddons-0.6.2.jar Refined Storage Addons {refinedstorageaddons@0.6.2 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		overloadedarmorbar-4.0.0.jar Overloaded Armor Bar {overloadedarmorbar@4.0.0 DONE}
		DefaultOptions_1.15.2-11.0.1.jar Default Options {defaultoptions@11.0.1 DONE}
	Kiwi Modules: 
		fruittrees:cherry
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
		kiwi:data
	[Psi] Active spell: None
	Patchouli open book context: n/a
	Launched Version: forge-31.2.21
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 980/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre30
	OptiFine Build: 20200622-083032
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 980/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Vaelzan** [comment]
Please try to use Discord for support first, there is a solution to the crash there already. But anyway - update the Polymorph mod to the latest version, it will resolve it. It's a conflict between Placebo and Polymorph.

**Comment by benjiben55** [comment]
Hello, thanks for the answer so fast.
I will do this next time on discord. Thanks and have a nice evening 😊

Gesendet von Mail für Windows 10

Von: Vaelzan
Gesendet: Mittwoch, 24. Juni 2020 18:14
An: ValhelsiaTeam/Valhelsia
Cc: benjiben55; Author
Betreff: Re: [ValhelsiaTeam/Valhelsia] String crafting crash (#105)

Please try to use Discord for support first, there is a solution to the crash there already. But anyway - update the Polymorph mod to the latest version, it will resolve it. It's a conflict between Placebo and Polymorph.
