### ISSUE TITLE
Dedicated server crash - infinite tick loop

### ISSUE THREAD

**Issue by dualmoon** [ValhelsiaTeam/Valhelsia#136]
Seeing a hard to trace issue where a dedicated server crashes seemingly randomly. Here's the head of a log file:

```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
    at net.minecraft.world.chunk.Chunk.func_177414_a(Chunk.java:488) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_chunkclass,pl:mixin:APP:phosphor.mixins.json:chunk.MixinChunk,pl:mixin:A,pl:runtimedistcleaner:A}
    at net.minecraft.world.World.func_175674_a(World.java:820) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.world.IEntityReader.func_72839_b(SourceFile:34) ~[?:?] {re:classloading,re:mixin}
    at net.minecraft.world.IEntityReader.func_223439_a(SourceFile:64) ~[?:?] {re:classloading,re:mixin}
    at net.minecraft.world.IWorld.func_223439_a(IWorld.java:79) ~[?:?] 
```

In the two separate cases I've seen this, one was a Linux dedicated server (my own VM host, 8 cpus, 16GB memory, 8GB max) and one was a Windows desktop. The Windows server was default generation, mine was terragen. In my case it was very early game, no tech yet, and I was exploring the map a bit. In the other case the server owner teleported to a waypoint and it crashed. In both cases, restarting the server is successful, but when the affected user logs in the server hang and crashes. I haven't been able to find anything more than this, unfortunately.

Full log - https://pastebin.com/pzqL57VZ

**Comment by dualmoon** [comment]
Update: the Windows admin was able to issue a command to kill all entities in the world and was able to log in after! I will test on mine as well.
