### ISSUE TITLE
Error while starting server

### ISSUE THREAD

**Issue by Miwoj01** [ValhelsiaTeam/Valhelsia#139]
[01:33:59] [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 
1 errors found

[01:33:59] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Solar Flux Reborn (solarflux) encountered an error during the load_registries event phase
§7null
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) ~[?:?] {re:classl
oading}
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:995) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classlo
ading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstrans
former:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}
[01:33:59] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/minecraft/
server/./crash-reports/crash-2020-07-07_01.33.59-server.txt
[01:33:59] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[01:33:59] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds

**Comment by Vaelzan** [comment]
You're almost certainly not using Java 8, which is required to run modded Minecraft servers. This sort of thing is also handled via Discord and not GitHub. We have a FAQ there which covers this.
