### ISSUE TITLE
Crash while generating/entering the nether

### ISSUE THREAD

**Issue by andrejsavikin** [ValhelsiaTeam/Valhelsia#188]
When I place down a nether portal and enter I it, after a few seconds I get kicked off the server with error "Internal Server Error". Attempting to join from that point onwards results in an Internal Server Error. I've fixed that by using an nbt editor to change my player dimension and position to overworld. Attempting to enter the nether again or deleting the nether and then regenerating it results in the same error. I'm using TerraForged for world gen.

```
[23:55:07] [Server thread/INFO]: Loading 0 chunks for dimension minecraft:the_nether
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize biomesoplenty.common.command.BiomeArgument@6074814a (class biomesoplenty.common.command.BiomeArgument) - will not be sent to client!
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize net.minecraftforge.server.command.ModIdArgument@4f6e06dc (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$18523/47821748@7240042d (class com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$18523/47821748) - will not be sent to client!
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$18545/1567930816@1e971a64 (class com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$18545/1567930816) - will not be sent to client!
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@3f6b59cb (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client!
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@e9479c2 (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client!
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize net.minecraftforge.server.command.ModIdArgument@1d6dab4 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize net.minecraftforge.server.command.EnumArgument@6720d824 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize net.minecraftforge.server.command.EnumArgument@4bb58f54 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize blusunrize.immersiveengineering.common.util.commands.CommandMineral$MineralArgument@7158e117 (class blusunrize.immersiveengineering.common.util.commands.CommandMineral$MineralArgument) - will not be sent to client!
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize net.minecraftforge.server.command.EnumArgument@4994c143 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[23:55:07] [Netty Epoll Server IO #11/ERROR]: Could not serialize com.ldtteam.structurize.commands.arguments.MultipleStringArgument@ae0f45c (class com.ldtteam.structurize.commands.arguments.MultipleStringArgument) - will not be sent to client!
[23:55:08] [Server thread/WARN]: Failed to handle packet for /*myclientip*:64458
net.minecraft.crash.ReportedException: Feature placement
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:424) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.gen.placement.Placement.func_214998_a(Placement.java:76) ~[?:?]
	at net.minecraft.world.gen.placement.ConfiguredPlacement.func_215093_a(SourceFile:36) ~[?:?]
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:21) ~[?:?]
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:14) ~[?:?]
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:53) ~[?:?]
	at net.minecraft.world.biome.Biome.func_203608_a(Biome.java:281) ~[?:?]
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:103) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:74) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:518) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:516) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_212]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_212]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_212]
[23:55:08] [Server thread/INFO]: Sava lost connection: Internal server error
[23:55:08] [Server thread/INFO]: §eSava left the game§r
[23:55:08] [Server thread/ERROR]: Failed to save chunk [-27, 26]
java.util.concurrent.CompletionException: net.minecraft.crash.ReportedException: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_212]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_212]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_212]
Caused by: net.minecraft.crash.ReportedException: Feature placement
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:529) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:516) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_212]
	... 11 more
Caused by: java.lang.NullPointerException
	at net.minecraft.world.gen.placement.Placement.func_214998_a(Placement.java:76) ~[?:?]
	at net.minecraft.world.gen.placement.ConfiguredPlacement.func_215093_a(SourceFile:36) ~[?:?]
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:21) ~[?:?]
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:14) ~[?:?]
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:53) ~[?:?]
	at net.minecraft.world.biome.Biome.func_203608_a(Biome.java:281) ~[?:?]
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:103) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:74) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:518) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:516) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_212]
	... 11 more
[23:55:09] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
```

**Comment by Vaelzan** [comment]
Update to the latest pack version.

**Comment by andrejsavikin** [comment]
Well this looks like it solved it, thought something like that would be mentioned in the changelog :/

**Comment by MokahTGS** [comment]
What caused this crash?  We had this as well.
