### ISSUE TITLE
[3.0.5] Crash on creating/joining world

### ISSUE THREAD

**Issue by Seegras** [ValhelsiaTeam/Valhelsia#195]
Last messages: 
```
[m[32m[13:21:45] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 94%
[m[32m[13:21:45] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Time elapsed: 10937 ms
[m[33m[13:21:45] [Server thread/WARN] [structurize/]: file:///home/user/lib/MultiMC/instances/Valhelsia%203%20-%201.16/minecraft/mods/structurize-0.13.20-ALPHA.jar
[m[33m[13:21:45] [Server thread/WARN] [structurize/]: /home/user/lib/MultiMC/instances/Valhelsia%203%20-%201.16/minecraft/mods/structurize-0.13.20-ALPHA.jar
[m[33m[13:21:45] [Server thread/WARN] [structurize/]: /assets/structurize
[m[32m[13:21:45] [Server thread/INFO] [structurize/]: Load huts or decorations from jar
[m[1;31m[13:21:45] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: javax/xml/bind/DatatypeConverter
	Index: 3
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2936/0x0000000840bc6440@5618e4b2
		2: net.minecraftforge.eventbus.EventBus$$Lambda$2936/0x0000000840bc6440@3fa57014
		3: ASM: class com.ldtteam.structurize.event.EventSubscriber onServerStarted(Lnet/minecraftforge/fml/event/server/FMLServerStartedEvent;)V
		4: net.minecraftforge.eventbus.EventBus$$Lambda$2936/0x0000000840bc6440@7560eb0
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.ldtteam.structurize.util.StructureUtils.calculateMD5(StructureUtils.java:48)
	at com.ldtteam.structurize.util.StructureUtils.calculateMD5(StructureUtils.java:108)
	at com.ldtteam.structurize.management.Structures.loadSchematicsForPrefix(Structures.java:333)
	at com.ldtteam.structurize.management.Structures.loadStyleMapsJar(Structures.java:238)
	at com.ldtteam.structurize.management.Structures.loadStyleMaps(Structures.java:145)
	at com.ldtteam.structurize.management.Structures.init(Structures.java:122)
	at com.ldtteam.structurize.event.EventSubscriber.onServerStarted(EventSubscriber.java:48)
	at net.minecraftforge.eventbus.ASMEventHandler_95_EventSubscriber_onServerStarted_FMLServerStartedEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:109)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:623)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:92)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 14 more

[m[1;31m[13:21:45] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.ldtteam.structurize.util.StructureUtils.calculateMD5(StructureUtils.java:48) ~[?:0.13.20-ALPHA] {re:classloading}
	at com.ldtteam.structurize.util.StructureUtils.calculateMD5(StructureUtils.java:108) ~[?:0.13.20-ALPHA] {re:classloading}
	at com.ldtteam.structurize.management.Structures.loadSchematicsForPrefix(Structures.java:333) ~[?:0.13.20-ALPHA] {re:classloading}
	at com.ldtteam.structurize.management.Structures.loadStyleMapsJar(Structures.java:238) ~[?:0.13.20-ALPHA] {re:classloading}
	at com.ldtteam.structurize.management.Structures.loadStyleMaps(Structures.java:145) ~[?:0.13.20-ALPHA] {re:classloading}
	at com.ldtteam.structurize.management.Structures.init(Structures.java:122) ~[?:0.13.20-ALPHA] {re:classloading}
	at com.ldtteam.structurize.event.EventSubscriber.onServerStarted(EventSubscriber.java:48) ~[?:0.13.20-ALPHA] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_95_EventSubscriber_onServerStarted_FMLServerStartedEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:109) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:623) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.lang.ClassLoader.findClass(ClassLoader.java:719) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:92) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
	... 14 more
Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" AL lib: (EE) alc_cleanup: 1 device not closed

Process exited with code 255.

```

**Comment by Vaelzan** [comment]
You should get support on Discord as per the README here.

But that looks like you're not using Java 8 like Minecraft requires.
