### ISSUE TITLE
Pressurized Reaction Chamber causing game crash

### ISSUE THREAD

**Issue by PrimeZzZz** [ValhelsiaTeam/Valhelsia#204]
Ive been experiencing a serious number of game crashes while im feeding my Pressurized Reaction Chamber Polonium others are also experiencing the same issue on my server.
You will only crash if youre within the range of 3-6 blocks.
Atleast thats what i have gathered.

`---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/27/20 12:45 AM
Description: Unexpected error

java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429) ~[guava-21.0.jar:?] {}
	at blusunrize.immersiveengineering.api.wires.LocalWireNetwork.unloadConnector(LocalWireNetwork.java:176) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.wires.GlobalWireNetwork.onConnectorUnload(GlobalWireNetwork.java:339) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.wires.ImmersiveConnectableTileEntity.onChunkUnloaded(ImmersiveConnectableTileEntity.java:158) ~[?:?] {re:classloading}
	at net.minecraft.world.World.lambda$tickBlockEntities$5(World.java:514) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.World$$Lambda$11621/1010810591.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476) ~[?:1.8.0_51] {}
	at net.minecraft.world.World.func_217391_K(World.java:514) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:228) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1456) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:927) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:581) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.70.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/939517171.call(Unknown Source) [forge-1.16.1-32.0.70.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at blusunrize.immersiveengineering.api.wires.LocalWireNetwork.unloadConnector(LocalWireNetwork.java:176)
	at blusunrize.immersiveengineering.api.wires.GlobalWireNetwork.onConnectorUnload(GlobalWireNetwork.java:339)
	at blusunrize.immersiveengineering.api.wires.ImmersiveConnectableTileEntity.onChunkUnloaded(ImmersiveConnectableTileEntity.java:158)
	at net.minecraft.world.World.lambda$tickBlockEntities$5(World.java:514)
	at net.minecraft.world.World$$Lambda$11621/1010810591.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476)
	at net.minecraft.world.World.func_217391_K(World.java:514)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:228)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['PrimeZzZz'/689545, l='ClientLevel', x=-1056.48, y=63.94, z=281.75]]
	Chunk stats: Client Chunk Cache: 729, 587
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,63,271), Chunk: (at 0,3,15 in -14,16; contains blocks -224,0,256 to -209,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 14994547 game time, 16899536 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:616)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1976)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:602)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/939517171.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5905461832 bytes (5631 MB) / 10468982784 bytes (9984 MB) up to 10468982784 bytes (9984 MB)
	CPUs: 4
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9984m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.70.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.70.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.70.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.70.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.16.1_HD_U_G2_pre4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.70.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.70
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		enchantedbookredesign-3.0.jar Enchanted Book Redesign {enchantedbookredesign@3.0 DONE}
		NetherPortalFix_1.16.1-7.0.0.jar NetherPortalFix {netherportalfix@7.0.0 DONE}
		curiousshulkerboxes-FORGE-1.16.1-3.0.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.16.1-3.0 DONE}
		pitg-1.16.1-1.3.0.jar Pane In The Glass {pitg@1.16.1-1.3.0 DONE}
		BetterTitleScreen-1.16.1-1.10.0.jar Better Title Screen {bettertitlescreen@1.16.1-1.10.0 DONE}
		XaerosWorldMap_1.7.4_Forge_1.16.1.jar Xaero's World Map {xaeroworldmap@1.7.4 DONE}
		CookingForBlockheads_1.16.1-9.0.0.jar Cooking for Blockheads {cookingforblockheads@9.0.0 DONE}
		Controlling-7.0.0.2.jar Controlling {controlling@7.0.0.2 DONE}
		ReAuth-1.16-Forge-3.9.0.jar ReAuth {reauth@3.9.0 DONE}
		Placebo-1.16.1-4.0.1.jar Placebo {placebo@4.0.1 DONE}
		randompatches-1.16.1-1.22.0.0.jar RandomPatches {randompatches@1.16.1-1.22.0.0 DONE}
		mcw-doors-1.0.0-mc1.16.1.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		MekanismGenerators-1.16.1-10.0.3.426.jar Mekanism: Generators {mekanismgenerators@10.0.3 DONE}
		SnowRealMagic-1.16.1-2.0.0.jar Snow! Real Magic! {snowrealmagic@2.0.0 DONE}
		JustEnoughResources-1.16.1-0.11.0.79.jar Just Enough Resources {jeresources@0.11.0.79 DONE}
		absentbydesign-1.16.1-1.1.0.jar Absent By Design Mod {absentbydesign@1.16.1-1.1.0 DONE}
		refinedstorage-1.9.2.jar Refined Storage {refinedstorage@1.9.2 DONE}
		structure-gel-api-1.16.1-1.1.1.jar Structure Gel API {structure_gel@1.1.1 DONE}
		PackMenu-1.16.1-2.0.0.jar Pack Menu {packmenu@2.0.0 DONE}
		industrial-foregoing-1.16.1-3.0.3-5935836.jar Industrial Foregoing {industrialforegoing@3.0.3 DONE}
		BiomesOPlenty-1.16.1-11.0.0.390-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.390 DONE}
		MekanismAdditions-1.16.1-10.0.3.426.jar Mekanism: Additions {mekanismadditions@10.0.3 DONE}
		valhelsia_structures-16.0.1.jar Valhelsia Structures {valhelsia_structures@16.0.1 DONE}
		curios-FORGE-1.16.1-3.0.jar Curios API {curios@FORGE-1.16.1-3.0 DONE}
		leap-1.16.1-1.0.1.jar Leap {leap@1.0.1 DONE}
		MekanismTools-1.16.1-10.0.3.426.jar Mekanism: Tools {mekanismtools@10.0.3 DONE}
		curiouselytra-FORGE-1.16.1-3.0.jar Curious Elytra {curiouselytra@FORGE-1.16.1-3.0 DONE}
		AI-Improvements-1.16.1-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		cherishedworlds-FORGE-1.16.1-4.0.jar Cherished Worlds {cherishedworlds@FORGE-1.16.1-4.0 DONE}
		cloth-config-forge-4.0.2.jar Cloth Config v4 API {cloth-config@4.0 DONE}
		BetterBurning-1.16.1-2.0.2.jar BetterBurning {betterburning@2.0.2 DONE}
		Incubation-1.16.1-1.1.0.jar Incubation {incubation@1.1.0 DONE}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		ServerTabInfo-1.16.1-1.2.7-alpha.jar Server Tab Info {servertabinfo@1.2.7-alpha DONE}
		BetterMineshaftsForge-1.16.1-1.3.jar YUNG's Better Mineshafts {bettermineshafts@1.16.1-1.3 DONE}
		BetterAdvancements-1.16.1-0.1.0.100.jar Better Advancements {betteradvancements@0.1.0.100 DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		Kiwi-1.16.1-3.1.3.jar Kiwi {kiwi@3.1.3 DONE}
		ClientTweaks_1.16.1-5.0.0.jar Client Tweaks {clienttweaks@5.0.0 DONE}
		TrashSlot_1.16.1-12.0.1.jar TrashSlot {trashslot@12.0.1 DONE}
		torchslabmod-1.16.1_v1.6.16.jar Torch Slab Mod {torchslabmod@1.6.16 DONE}
		mining-helmet-1.16.1-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		OldJavaWarning-1.16.1-4.0.1.jar OldJavaWarning {oldjavawarning@4.0.1 DONE}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
		JEIEnchantmentInfo-1.16.1-1.1.0.jar JEI Enchantment Info {jeienchantmentinfo@1.16.1-1.0.0 DONE}
		the-conjurer-1.16.1-1.0.6.jar The Conjurer {conjurer_illager@1.0.6 DONE}
		Abnormals-Core-1.16.1-v2.0.0.jar Abnormals Core {abnormals_core@2.0.0 DONE}
		Bamboo-Blocks-1.16.1-2.0.0.jar Bamboo Blocks {bamboo_blocks@NONE DONE}
		Buzzier-Bees-1.16.1-2.0.0.jar Buzzier Bees {buzzier_bees@2.0.0 DONE}
		Mekanism-1.16.1-10.0.3.426.jar Mekanism {mekanism@10.0.3 DONE}
		caelus-FORGE-1.16.1-2.0-beta5.jar Caelus API {caelus@FORGE-1.16.1-2.0-beta5 DONE}
		Extra-Boats-1.16.1-1.4.0.jar Extra Boats {extraboats@1.4.0 DONE}
		Waystones_1.16.1-7.0.2.jar Waystones {waystones@7.0.2 DONE}
		Clumps-6.0.0.3.jar Clumps {clumps@6.0.0.3 DONE}
		light-overlay-5.4.1.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		comforts-FORGE-1.16.1-3.0.jar Comforts {comforts@FORGE-1.16.1-3.0 DONE}
		NaturesCompass-1.16.1-1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 DONE}
		decorative_blocks-7a.jar Decorative Blocks {decorative_blocks@7a DONE}
		curioofundying-FORGE-1.16.1-4.0.jar Curio of Undying {curioofundying@FORGE-1.16.1-4.0 DONE}
		snowundertrees-1.16.1-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		bedspreads-FORGE-1.16.1-4.0.jar Bedspreads {bedspreads@FORGE-1.16.1-4.0 DONE}
		ToastControl-1.16.1-4.0.0.jar Toast Control {toastcontrol@4.0.0 DONE}
		JEITweaker-1.16.1-1.0.1.2.jar JEI Tweaker {jeitweaker@1.0.1.2 DONE}
		CraftTweaker-1.16.1-7.0.0.13.jar CraftTweaker {crafttweaker@7.0.0.13 DONE}
		forge-1.16.1-32.0.70-universal.jar Forge {forge@32.0.70 DONE}
		Waddles-1.16.1-0.8.7.jar Waddles {waddles@1.16.1-0.8.7 DONE}
		Bones-1.16.1-1.3.2.jar Bones {bones@1.16.1-1.3.2 DONE}
		dash-1.16.1-1.0.1.jar Dash {dash@1.0.1 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		CraftingTweaks_1.16.1-12.0.4.jar Crafting Tweaks {craftingtweaks@12.0.4 DONE}
		forge-1.16.1-32.0.70-client.jar Minecraft {minecraft@1.16.1 DONE}
		The-Endergetic-Expansion-1.16.1-2.0.0.jar The Endergetic Expansion {endergetic@2.0.0 DONE}
		MouseTweaks-2.13-mc1.16.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.16.1-3.0.2.jar Titanium {titanium@3.0.2 DONE}
		ImmersiveEngineering-0.16-109.jar Immersive Engineering {immersiveengineering@0.16-109 DONE}
		forbidden_arcanus-1.16.1-1.0-beta-2.jar Forbidden & Arcanus {forbidden_arcanus@1.16.1-1.0-beta DONE}
		Savage-and-Ravage-1.16.1-2.0.0.jar Savage & Ravage {savageandravage@2.0.0 DONE}
		Xaeros_Minimap_20.17.0_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.17.0 DONE}
		pamhc2foodcore-1.16.1-1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		serverconfigupdater-1.2.jar ServerConfig Updater {serverconfigupdater@1.2 DONE}
		lava-monster-1.16.1-1.0.7.jar Lava Monster {lava_monster@1.0.7 DONE}
		FastWorkbench-1.16.1-4.1.1.jar FastWorkbench {fastbench@4.1.1 DONE}
		polymorph-FORGE-1.16.1-0.11.jar Polymorph {polymorph@FORGE-1.16.1-0.11 DONE}
		AutoRegLib-1.6-42.jar AutoRegLib {autoreglib@1.6-42 DONE}
		Quark-r2.2-255.jar Quark {quark@r2.2-255 DONE}
		Enhanced-Mushrooms-1.16.1-v2.0.3.jar Enhanced Mushrooms {enhanced_mushrooms@2.0.0 DONE}
		StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 DONE}
		DoubleSlabs-1.16-3.2.0.jar Double Slabs {doubleslabs@3.2.0 DONE}
		InventoryHud_1.16.1.forge-3.0.1.jar Inventory HUD+(Forge edition) {inventoryhud@3.0.1 DONE}
		structurize-0.13.20-ALPHA.jar Structurize {structurize@0.13.20-ALPHA DONE}
		FastFurnace-1.16.1-4.0.0.jar FastFurnace {fastfurnace@4.0.0 DONE}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.16.1-1.1.1-b3.jar Engineer's Decor {engineersdecor@1.1.1-b3 DONE}
		refinedstorageaddons-0.7.jar Refined Storage Addons {refinedstorageaddons@0.7 DONE}
		CosmeticArmorReworked-1.16.1-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.1-v1a DONE}
		overloadedarmorbar-5.0.0.jar Overloaded Armor Bar {overloadedarmorbar@5.0.0 DONE}
		step-1.16.1-1.0.2.jar Step {step@1.0.2 DONE}
		DefaultOptions_1.16.1-12.0.1.jar Default Options {defaultoptions@12.0.1 DONE}
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
	Launched Version: forge-32.0.70
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.28, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, packmenu
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre4
	OptiFine Build: 20200711-211327
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.27 High.zip
	OpenGlVersion: 4.6.0 NVIDIA 441.28
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4`

**Comment by Khytwel** [comment]
I didn't manage to reproduce this bug, so if this one comes back I invite you to reopen the issue.
