### ISSUE TITLE
Game instantly crashes after opening, has very vague log.

### ISSUE THREAD

**Issue by skylerspark** [ValhelsiaTeam/Valhelsia#74]
So my sister wants to use the Valhesia Modpack on her server, I got it running on her server, but when I downloaded it on twitch for her, and tried running it, it instantly crashes after running.

I honestly only know so much about mods, and I tried digging through the log myself, but I didnt get anywhere with it.

In the attachments, Ive included the GZ log. The plaintext log is here:

`[13:55:31] [main/INFO]: ModLauncher running: args [--username, WaffleCum, --version, forge-31.2.0, --gameDir, C:\Users\Devin Schneider\Twitch\Minecraft\Instances\Valhelsia 2, --assetsDir, C:\Users\Devin Schneider\Twitch\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, 03d27e7e7023463cba5e51e60592a248, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.0, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[13:55:31] [main/INFO]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_51 by Oracle Corporation
[13:55:31] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[13:55:32] [main/FATAL]: Failed to find Minecraft resource version 1.15.2-20200515.085601 at C:\Users\Devin Schneider\Twitch\Minecraft\Install\libraries\net\minecraftforge\forge\1.15.2-31.2.0\forge-1.15.2-31.2.0-client.jar
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Missing minecraft resource!
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler$$Lambda$154/259219561.accept(Unknown Source)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:197)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:92)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$86/1423561005.accept(Unknown Source)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[13:55:32] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
`

[2020-06-08-4.log.gz](https://github.com/ValhelsiaTeam/Valhelsia/files/4747818/2020-06-08-4.log.gz)

**Comment by someaddons** [comment]
use gist

**Comment by madhatr** [comment]
I'd remove your personal info from your post.

Try bypassing twitch launcher, found this guys video for that [here](https://youtu.be/kIUEK14_0s8)

I use multiMC to manage twitch/curseforge mods packs, works great.

**Comment by Vaelzan** [comment]
Read the README before submitting issues: https://github.com/ValhelsiaTeam/Valhelsia/issues/5

This particular bug with Twitch is dealt with in the FAQ on Discord, and that is where we handle all technical support. https://discordapp.com/invite/reQZEXu
