### ISSUE TITLE
Resolved - FruitTrees Mod crashes game on load (Twitch & FML not playing nice)

### ISSUE THREAD

**Issue by mdinnocenzo** [ValhelsiaTeam/Valhelsia#94]
[16:26:26] [main/INFO]: ModLauncher running: args [--username, SideSh0wWilly, --version, forge-31.2.21, --gameDir, C:\Users\dino.BYTESBREAK\Twitch\Minecraft\Instances\Valhelsia 2, --assetsDir, C:\Users\dino.BYTESBREAK\Twitch\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, d50c368e13ef4011a95aa756183acfc4, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.21, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[16:26:26] [main/INFO]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_251 by Oracle Corporation
[16:26:26] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[16:26:26] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/dino.BYTESBREAK/Twitch/Minecraft/Instances/Valhelsia%202/mods/MixinBootstrap-1.0.3.jar Service=ModLauncher Env=CLIENT
[16:26:27] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:99 token recognition error at: ';'
[16:26:28] [main/INFO]: Successfully loaded Mixin Connector [snownee.fruits.mixin.Connector]
[16:26:28] [main/INFO]: Successfully loaded Mixin Connector [me.jellysquid.mods.phosphor.mixin.PhosphorMixinConnector]
[16:26:28] [main/INFO]: Invoking Mixin Connector
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: net/minecraft/state/IProperty
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at snownee.fruits.mixin.Connector.connect(Connector.java:15)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.initConnectors(MixinConnectorManager.java:96)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:61)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:194)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$12(LaunchPluginHandler.java:95)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.HashMap.forEach(Unknown Source)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:95)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.state.IProperty
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.findClass(Unknown Source)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:26:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 13 more

**Comment by mdinnocenzo** [comment]
Twitch and FML broken, was able to resolve it with a reload of the 1.5.2 FML folders for twitch.

**Comment by dannypas00** [comment]
Getting a similar problem trying to run the 2.2.3 server for the first time on linux.
https://pastebin.com/9znZfCYH
